// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVPMhug-jsTPiGWYfKW0SEy0FxDrLPjQg',
    appId: '1:186295789473:web:4214d7e324461c46e58de0',
    messagingSenderId: '186295789473',
    projectId: 'foodie-56500',
    authDomain: 'foodie-56500.firebaseapp.com',
    storageBucket: 'foodie-56500.appspot.com',
    measurementId: 'G-RM2DV10JLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA81Fea3G02Jn0ys-JJTRBzTvdGXkcbY1c',
    appId: '1:186295789473:android:4bc5e20e111b1256e58de0',
    messagingSenderId: '186295789473',
    projectId: 'foodie-56500',
    storageBucket: 'foodie-56500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8MVq6r6ChhuiS7VXbdRU_PRb7zFbraPY',
    appId: '1:186295789473:ios:525423da00f3f342e58de0',
    messagingSenderId: '186295789473',
    projectId: 'foodie-56500',
    storageBucket: 'foodie-56500.appspot.com',
    iosClientId:
        '186295789473-od3m8fjl9cv4p84tp4m8tam9p7hi6389.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8MVq6r6ChhuiS7VXbdRU_PRb7zFbraPY',
    appId: '1:186295789473:ios:525423da00f3f342e58de0',
    messagingSenderId: '186295789473',
    projectId: 'foodie-56500',
    storageBucket: 'foodie-56500.appspot.com',
    iosClientId:
        '186295789473-od3m8fjl9cv4p84tp4m8tam9p7hi6389.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodie',
  );
}
